### ISSUE TITLE
Setup of kanban board

### ISSUE THREAD

**Issue by Lucash2022** [Lucash2022/Catalog-Ruby-Group-Capstone#23]
Link to Kanban project - https://github.com/Lucash2022/Catalog-Ruby-Group-Capstone/projects/1 

We are three in this group
Team member 1 -Lucas Erkana @Lucash2022 
Team member 2 - Ghulam Hyder Dar @codeWithHyder 
Team member 3 - Mbale Christian Kagheni @Kaghenimbale

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- good job setting up the kanban board

## Required Changes ♻️
- [ ] for group member 1 the following cards are missing:
  - Add unit tests for all implemented methods.
  - The following options should be available:
      - List all books
      - List all labels (e.g. 'Gift', 'New')
      - Add a book
- [ ] for group member 2 the following point should be on a separate card:
  - All MusicAlbum class properties visible in the diagram should be defined and set up in the constructor method.
- [ ] for group member 3 the following points should be split into 2 cards:
  - All Game class properties visible in the diagram should be defined and set up in the constructor method.
  - All Author class properties visible in the diagram should be defined and set up in the constructor method.
- [ ] for the group tasks there should be a separate card for each bullet point in the list of requirements:

- Create Item class in a separate .rb file.
- All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
- Add all methods visible in the diagram.
- Implement methods:
    - can_be_archived?() in the Item class
        - should return true if published_date is older than 10 years
        - otherwise, it should return false
    - move_to_archive() in the Item class
        - should reuse can_be_archived?() method
        - should change the archived property to true if the result of the can_be_archived?() method is true
        - should do nothing if the result of the can_be_archived?() method is false
- Create a main.rb file that will serve as your console app entry-point.
- Implement startup actions:
    - Present the user with a list of options to perform.
    - Let users choose an option.
    - If needed, ask for parameters for the option.
    - Have a way to quit the app.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lucash2022** [comment]
Thank you for the review. We have rectified all errors.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Lucash2022, @codeWithHyder and @Kaghenimbale,

✔️ Tasks are properly assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
